#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jan 12 21:36:49 EST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=Sildur's Enhanced Default v1.171 Fancy.zip
enableShaders=false
